/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddIcon: typeof import('./src/components/icons/AddIcon.vue')['default']
    AttrEmptyIcon: typeof import('./src/components/icons/AttrEmptyIcon.vue')['default']
    AudioIcon: typeof import('./src/components/icons/AudioIcon.vue')['default']
    AudioResourceItem: typeof import('./src/components/item/resourcesItem/AudioResourceItem.vue')['default']
    CanvasPlayer: typeof import('./src/components/container/CanvasPlayer.vue')['default']
    DeleteIcon: typeof import('./src/components/icons/DeleteIcon.vue')['default']
    EffectsIcon: typeof import('./src/components/icons/EffectsIcon.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FilterIcon: typeof import('./src/components/icons/FilterIcon.vue')['default']
    HeaderContainer: typeof import('./src/components/container/HeaderContainer.vue')['default']
    ImageIcon: typeof import('./src/components/icons/ImageIcon.vue')['default']
    ItemList: typeof import('./src/components/ItemList.vue')['default']
    MenuList: typeof import('./src/components/MenuList.vue')['default']
    OtherResource: typeof import('./src/components/item/resourcesItem/OtherResource.vue')['default']
    Player: typeof import('./src/components/item/player/Player.vue')['default']
    RedoIcon: typeof import('./src/components/icons/RedoIcon.vue')['default']
    ResourcesContainer: typeof import('./src/components/container/ResourcesContainer.vue')['default']
    ResourcesItem: typeof import('./src/components/item/resourcesItem/AudioResourceItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplitIcon: typeof import('./src/components/icons/SplitIcon.vue')['default']
    SplitLine: typeof import('./src/components/SplitLine.vue')['default']
    SubIcon: typeof import('./src/components/icons/SubIcon.vue')['default']
    SubList: typeof import('./src/components/SubList.vue')['default']
    TextIcon: typeof import('./src/components/icons/TextIcon.vue')['default']
    TimeLine: typeof import('./src/components/item/trackItem/TimeLine.vue')['default']
    TrackContainer: typeof import('./src/components/container/TrackContainer.vue')['default']
    TrackContro: typeof import('./src/components/item/trackItem/TrackContro.vue')['default']
    TrackControl: typeof import('./src/components/item/trackItem/TrackControl.vue')['default']
    TrackList: typeof import('./src/components/TrackList.vue')['default']
    TrackListIcon: typeof import('./src/components/item/trackItem/TrackListIcon.vue')['default']
    TransitionIcon: typeof import('./src/components/icons/TransitionIcon.vue')['default']
    UndoIcon: typeof import('./src/components/icons/UndoIcon.vue')['default']
    VideoIcon: typeof import('./src/components/icons/VideoIcon.vue')['default']
  }
}
